# Generated by Django 3.0.2 on 2020-01-18 22:36

from django.db import migrations
import spkcspider.apps.spider.models.content_extended


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spider_base', '0014_authtoken_attached_to_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('spider_base.datacontent',),
            managers=[
                ('objects', spkcspider.apps.spider.models.content_extended.DataContentManager()),
            ],
        ),
        migrations.CreateModel(
            name='PostBox',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('spider_base.datacontent',),
            managers=[
                ('objects', spkcspider.apps.spider.models.content_extended.DataContentManager()),
            ],
        ),
        migrations.CreateModel(
            name='WebReference',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('spider_base.datacontent',),
            managers=[
                ('objects', spkcspider.apps.spider.models.content_extended.DataContentManager()),
            ],
        ),
    ]
